PUT http://0.0.0.0:8080/events/2
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IjJAbWFpbC5jb20iLCJleHAiOjE3MjMxMzYxMzksInVzZXJJZCI6Mn0.pkp4iuiJqD0UMWPARtASJttSfB-ctvcy8iKDQL09ztI

{
  "name": "name for this event",
  "description": "some nie event",
  "location": "asdadsad",
  "dateTime": "2025-01-01T00:00:00Z"
}